import jsPDF from 'jspdf';

/**
 * Generates a black-and-white PDF class report.
 * @param {Object} analytics - Analytics data object
 * @param {string} analytics.className - Class name
 * @param {string} analytics.teacherName - Teacher name
 * @param {Array} analytics.students - Array of student objects
 * @returns {void} - Triggers PDF download
 */
export function generateClassReport(analytics) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont('courier', 'bold');
  doc.text('Newton AI — Class Report', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('courier', 'normal');
  doc.text(`Class: ${analytics.className || 'Unknown'}`, margin, y);
  y += 5;
  doc.text(`Teacher: ${analytics.teacherName || 'Unknown'}`, margin, y);
  y += 5;
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, y);
  y += 10;

  // Summary
  doc.setFont('courier', 'bold');
  doc.text('Summary', margin, y);
  y += 6;
  doc.setFont('courier', 'normal');

  const students = analytics.students || [];
  const avgMastery = students.length > 0
    ? Math.round(students.reduce((sum, s) => sum + (s.mastery || 0), 0) / students.length)
    : 0;
  const totalFlags = students.reduce((sum, s) => sum + (s.integrityFlags || 0), 0);

  doc.text(`Total Students: ${students.length}`, margin, y); y += 5;
  doc.text(`Average Mastery: ${avgMastery}%`, margin, y); y += 5;
  doc.text(`Integrity Incidents: ${totalFlags}`, margin, y); y += 10;

  // Table header
  doc.setFont('courier', 'bold');
  const cols = [margin, 70, 95, 120, 145, 170];
  const headers = ['Student', 'Mastery', 'Topics', 'Flags', 'Last Active'];
  headers.forEach((h, i) => doc.text(h, cols[i], y));
  y += 2;
  doc.line(margin, y, 190, y);
  y += 5;

  // Table rows
  doc.setFont('courier', 'normal');
  doc.setFontSize(9);
  for (const student of students) {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
    const name = (student.name || student.email || 'Unknown').slice(0, 20);
    doc.text(name, cols[0], y);
    doc.text(`${student.mastery || 0}%`, cols[1], y);
    doc.text(`${student.topicsCovered || 0}`, cols[2], y);
    doc.text(`${student.integrityFlags || 0}`, cols[3], y);
    doc.text(student.lastActive ? new Date(student.lastActive).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : '—', cols[4], y);
    y += 5;
  }

  // Footer
  y += 5;
  doc.setFontSize(8);
  doc.text(`Generated by Newton AI — ${new Date().toLocaleDateString('en-GB')}`, margin, y);

  doc.save(`newton-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
